dbt_trino:
  outputs:
    trino_output:
      type: trino
      method: basic
      user: "{{ env_var('TRINO_USERNAME', 'trino') }}"
      password: "{{ env_var('TRINO_PASSWORD') }}"
      database: iceberg
      host: trino-coordinator
      port: 8080
      schema: staging
      threads: 1
      http_scheme: http
  target: trino_output